language: node_js
node_js:
  - node
  - lts/*
env:
  - NODE_OPTIONS="--experimental-modules"
install:
  - npm install
script:
  - npm run all
after_success:
  - bash <(curl -s https://codecov.io/bash)
