name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: node common/scripts/install-run-rush.js install
    - name: Build the project
      run: node common/scripts/install-run-rush.js all
    - name: Send coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
